server:
  port: ${ihub.application.port}
spring:
  application:
    name: ${ihub.application.prefix}-${ihub.application.name}
  output:
    ansi:
      enabled: always
ihub:
  application:
    prefix: ihub
    gateway-server-addr: localhost
management.endpoints.web.exposure.include: "*"
