spring:
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: ${ihub.secure.provider}
            client-id: ${ihub.secure.client-id}
            client-secret: ${ihub.secure.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: ${ihub.secure.client-id}-oidc
          messaging-client-authorization-code:
            provider: ${ihub.secure.provider}
            client-id: ${ihub.secure.client-id}
            client-secret: ${ihub.secure.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized"
            scope: ${ihub.secure.scope}
            client-name: ${ihub.secure.client-id}-authorization-code
          messaging-client-client-credentials:
            provider: ${ihub.secure.provider}
            client-id: ${ihub.secure.client-id}
            client-secret: ${ihub.secure.client-secret}
            authorization-grant-type: client_credentials
            scope: ${ihub.secure.scope}
            client-name: ${ihub.secure.client-id}-client-credentials
        provider:
          ihub:
            issuer-uri: http://auth-server:9000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
ihub:
  secure:
    provider: ihub
    client-id: messaging-client
    client-secret: secret
    scope: message.read,message.write
