name: Gradle Dependency Submission
on:
  push:
    branches:
      - main

jobs:
  gradle-action-detection:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          egress-policy: block

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.8.5
        with:
          gradle-project-path: ""
          gradle-build-module: ":"
